fix pulling single file in a directory
semaphoreci/artifact pull request #25
Opened 2020-12-14 11:20 UTC by horace-stavropoulos

When pulling, and there's only one signed url:
  checking if the signed url matches the given name

2020-12-14 11:29 UTC, AleksandarCole commented
Corresponding ticket: https://github.com/renderedtext/issues/issues/2636

2020-12-14 12:22 UTC, shiroyasha commented on pkg/gcs/gcs.go
> +func strIndexByteNthAfter(s string, b byte, count int) string {
The name of this function is not clear. What is the job of this function?

2020-12-14 12:23 UTC, shiroyasha commented on pkg/gcs/gcs.go
> +	}
The complexity of the PullGCS function is too high, please extract the logic from this if to a dedicated function.

2020-12-14 12:25 UTC, shiroyasha requested changes
The initial code looks good. We need two things before we can proceed:

- Cover this behavior with tests.
- The new code increases the cognitive load of the PullGCS function. Some slight refactoring is needed.

2020-12-18 12:50 UTC, shiroyasha approved these changes

2020-12-23 13:21 UTC, merged