Use stdin to push artifacts
semaphoreci/artifact pull request #40
Opened 2022-05-17 21:50 UTC by lucaspin

## Push using stdin

```
» docker image save alpine/helm | gzip | ./artifact push job - -d alpine-image -v -f
...
2022/05/17 18:46:36 Detected stdin, saving it to a temporary file...
2022-05-17T18:46:36.952-0300	DEBUG	log/log.go:85	Detected stdin, saving it to a temporary file...
2022/05/17 18:46:44 PushPaths
2022-05-17T18:46:44.243-0300	DEBUG	log/log.go:85	PushPaths	{"input destination": "alpine-image", "input source": "/var/folders/qz/fys7r29s4cz9l_rn8zsmssz80000gn/T/982060311", "output destination": "artifacts/jobs/9eb052ad-a4c5-4570-91e8-94539d7320b6/alpine-image", "output source": "/var/folders/qz/fys7r29s4cz9l_rn8zsmssz80000gn/T/982060311"}
2022/05/17 18:46:44 pushing...
2022-05-17T18:46:44.255-0300	DEBUG	log/log.go:85	pushing...	{"source": "/var/folders/qz/fys7r29s4cz9l_rn8zsmssz80000gn/T/982060311", "destination": "artifacts/jobs/9eb052ad-a4c5-4570-91e8-94539d7320b6/alpine-image", "force": true}
2022/05/17 18:46:44 the source seems to be a file
2022-05-17T18:46:44.255-0300	DEBUG	log/log.go:85	the source seems to be a file	{"source": "/var/folders/qz/fys7r29s4cz9l_rn8zsmssz80000gn/T/982060311"}
2022/05/17 18:46:44 Uploading...
2022-05-17T18:46:44.620-0300	DEBUG	log/log.go:85	Uploading...	{"source": "/var/folders/qz/fys7r29s4cz9l_rn8zsmssz80000gn/T/982060311", "destination": "artifacts/jobs/9eb052ad-a4c5-4570-91e8-94539d7320b6/alpine-image"}
2022/05/17 18:46:48 successful push for current job
2022-05-17T18:46:48.091-0300	INFO	log/log.go:78	successful push for current job	{"source": "/var/folders/qz/fys7r29s4cz9l_rn8zsmssz80000gn/T/982060311", "destination": "artifacts/jobs/9eb052ad-a4c5-4570-91e8-94539d7320b6/alpine-image"}
```

## Push using regular file

```
» ./artifact push job README.md -v
...
2022-05-17T18:49:49.837-0300	DEBUG	log/log.go:85	PushPaths	{"input destination": "", "input source": "README.md", "output destination": "artifacts/jobs/9eb052ad-a4c5-4570-91e8-94539d7320b6/README.md", "output source": "README.md"}
2022/05/17 18:49:49 pushing...
2022-05-17T18:49:49.837-0300	DEBUG	log/log.go:85	pushing...	{"source": "README.md", "destination": "artifacts/jobs/9eb052ad-a4c5-4570-91e8-94539d7320b6/README.md", "force": false}
2022/05/17 18:49:49 the source seems to be a file
2022-05-17T18:49:49.837-0300	DEBUG	log/log.go:85	the source seems to be a file	{"source": "README.md"}
2022/05/17 18:49:50 Uploading...
2022-05-17T18:49:50.588-0300	DEBUG	log/log.go:85	Uploading...	{"source": "README.md", "destination": "artifacts/jobs/9eb052ad-a4c5-4570-91e8-94539d7320b6/README.md"}
2022/05/17 18:49:50 successful push for current job
2022-05-17T18:49:50.839-0300	INFO	log/log.go:78	successful push for current job	{"source": "README.md", "destination": "artifacts/jobs/9eb052ad-a4c5-4570-91e8-94539d7320b6/README.md"}
```

2022-05-18 08:13 UTC, shiroyasha requested changes
As this could be a feature that breaks some existing workflows, I think we need to cover it with some hardcore e2e tests.

2022-05-18 11:51 UTC, lucaspin commented
@shiroyasha we currently have E2E tests for artifacts [in the toolbox](https://github.com/semaphoreci/toolbox/blob/master/tests/artifacts.bats) only, so I was thinking about adding the tests there. Do you think we should add something here? If so, I think it might be best to mock artifacthub somehow and use a storage emulator. What do you think?

2022-05-18 12:10 UTC, shiroyasha commented
Having it in the toolbox only also makes sense 👍

2022-05-18 12:14 UTC, shiroyasha approved these changes

2022-05-18 12:15 UTC, merged

2022-06-22 15:22 UTC, sirianni commented
@lucaspin 

This change seems to be breaking our semaphore builds.  Even though we are passing a filename, the process seems to be hanging waiting for `stdin`.

```
artifact push project --force target/generated-resources/docs/docs/openapi.html
```